export const data = {
  name: "Emiliano Montoya Velázquez",
  nameShort: "Emiliano Montoya",
  initials: "EMV",
  title: "Ingeniero en Sistemas Computacionales",
  subtitle: "Full Stack Developer",
  location: "Tehuacán, Puebla, México",
  bio: "Estudiante de Ingeniería en Sistemas con fuerte interés en desarrollo de software, optimización de procesos y gestión de bases de datos. Busco aplicar mis conocimientos en organizaciones que fomenten la innovación tecnológica y el desarrollo de soluciones eficientes.",
  available: true,

  contact: {
    phone: "238 224 0062",
    email: "emilianomontoya1109@gmail.com",
    github: "https://github.com/MontoyaEmiliano",
    githubHandle: "MontoyaEmiliano",
    location: "Tehuacán, Puebla",
  },

  skills: [
    { name: "React",       icon: "⚛️",  level: 82, category: "Frontend" },
    { name: "Node.js",     icon: "🟢",  level: 78, category: "Backend"  },
    { name: "Python",      icon: "🐍",  level: 75, category: "Backend"  },
    { name: "JavaScript",  icon: "🟡",  level: 80, category: "Frontend" },
    { name: "MySQL",       icon: "🗄️",  level: 72, category: "DB"       },
    { name: "APIs REST",   icon: "🔗",  level: 76, category: "Backend"  },
    { name: "TypeScript",  icon: "🔷",  level: 65, category: "Frontend" },
    { name: "Tailwind CSS",icon: "🎨",  level: 70, category: "Frontend" },
    { name: "C",           icon: "⚙️",  level: 60, category: "General"  },
    { name: "Excel / Office", icon: "📊", level: 90, category: "General" },
  ],

  areasInteres: [
    { icon: "🤖", label: "Desarrollo IA" },
    { icon: "🗄️", label: "Administración BD" },
    { icon: "📦", label: "Logística Empresarial" },
    { icon: "🖥️", label: "Mantenimiento Servidores" },
  ],

  idiomas: [
    { name: "Español", level: "Nativo",     flag: "🇲🇽" },
    { name: "Inglés",  level: "TOEFL",      flag: "🇺🇸" },
  ],

  projects: [
    {
      id: 1,
      icon: "💞",
      color: "#ff6b9d",
      featured: true,
      title: "Allora — App Social Móvil",
      description: "Aplicación móvil multiplataforma (iOS/Android) con sistema de autenticación JWT, chat en tiempo real vía WebSocket, radar de ubicación en vivo y sistema de matches entre usuarios. Arquitectura orientada a servicios con API REST en el backend.",
      tags: ["React Native", "Expo", "TypeScript", "WebSocket", "JWT", "REST API"],
      github: "https://github.com/BERNARDOBOJALIL/FrontendAllora",
      demo: "",
      year: "2026",
    },
    {
      id: 2,
      icon: "🌐",
      color: "#00E5CC",
      title: "Web Corporativa — Manufactura Textil",
      description: "Diseño, creación y administración del sitio web y redes sociales de la empresa Manufactura Textil Tehuacán. Gestión de contenido digital y presencia en línea.",
      tags: ["HTML/CSS", "JavaScript", "Redes Sociales", "Diseño Web"],
      github: "",
      demo: "",
      year: "2021–2023",
    },
    {
      id: 3,
      icon: "🔗",
      color: "#A78BFA",
      title: "Integración de APIs REST",
      description: "Desarrollo de servicios backend con integración de APIs externas usando Node.js. Manejo de autenticación, peticiones HTTP y gestión de respuestas JSON.",
      tags: ["Node.js", "REST API", "JavaScript", "JSON"],
      github: "https://github.com/MontoyaEmiliano",
      demo: "",
      year: "2024",
    },
    {
      id: 4,
      icon: "🖥️",
      color: "#38BDF8",
      title: "PantallaRafa — Dashboard Interactivo",
      description: "Dashboard web con login, widgets en tiempo real: clima, GIFs del día, estadísticas del sistema, lista de tareas, feed en vivo, juego oculto y terminal de tips. Interfaz modular construida con React + Vite.",
      tags: ["React", "Vite", "APIs externas", "Dashboard", "JavaScript"],
      github: "https://github.com/MontoyaEmiliano/PantallaRafa",
      demo: "",
      year: "2025",
    },
    {
      id: 5,
      icon: "🤖",
      color: "#4ADE80",
      title: "Agente Inteligente — Curador de Artículos",
      description: "Sistema full stack con agente IA que busca, resume, etiqueta y gestiona artículos. Backend en Python (FastAPI), frontend en React + Tailwind con vistas de búsqueda, historial, estadísticas y gestión de etiquetas.",
      tags: ["Python", "FastAPI", "React", "Tailwind CSS", "IA", "Vite"],
      github: "https://github.com/MontoyaEmiliano/Agente_Inteligente",
      demo: "",
      year: "2025",
    },
  ],

  experience: [
    {
      icon: "🏭",
      title: "Logística, Administración & Web",
      company: "Manufactura Textil Tehuacán",
      location: "Tehuacán, Pue.",
      period: "2021 – 2023",
      desc: "Envíos y entregas de mercancía, trabajo en empaque y logística. Creación y administración de redes sociales y página web de la empresa.",
      type: "work",
    },
  ],

  education: [
    {
      icon: "🎓",
      title: "Ingeniería en Sistemas Computacionales",
      company: "Ibero Puebla",
      location: "Puebla",
      period: "2022 – presente",
      desc: "Formación en desarrollo de software, bases de datos, implementación de sistemas inteligentes y proyectos computacionales.",
      type: "edu",
    },
    {
      icon: "🌎",
      title: "Certificación TOEFL — Inglés",
      company: "Ibero Puebla",
      location: "Puebla",
      period: "2022 – 2025",
      desc: "Certificación internacional de dominio del idioma inglés.",
      type: "edu",
    },
    {
      icon: "📊",
      title: "Certificación Microsoft Office",
      company: "Colegio Karol Wojtyla",
      location: "Tehuacán",
      period: "2019 – 2021",
      desc: "Certificado en Excel, PowerPoint y Word en 3 años.",
      type: "cert",
    },
  ],

  competencias: [
    "Desarrollo de software computacional",
    "Desarrollo de aplicaciones para sistemas de cómputo",
    "Implementación de sistemas computacionales inteligentes",
    "Desarrollo de proyectos en sistemas computacionales",
    "Competencia digital",
    "Trabajo colaborativo",
  ],
};
